name: daily_helper
description: Apps to help you on your daily routine

version: 1.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  url_launcher: ^5.4.2
  path_provider: ^1.6.5
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

  assets:
    - lang/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/daily_helper_icon.png"